apiVersion: v1
kind: Service
metadata:
  name: jewellary-static
  namespace: static
spec:
  selector:
    app: jewellery-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
